#!/bin/bash

set -e

# Eeprom
dtc -@ -I dts -O dtb -o /usr/local/lib/wand/iolib/eepromLib/at24c512.dtbo /usr/local/lib/wand/iolib/eepromLib/at24c512.dts
cp /usr/local/lib/wand/iolib/eepromLib/at24c512.dtbo /boot/overlays/at24c512.dtbo

bash /usr/local/lib/wand/iolib/buttonLib/cap1293/cap12xx_v2/install_kernel_module.sh
bash /usr/local/lib/wand/iolib/lp5562/kernel_drivers/install_kernel_module.sh


# neopixel as a service
cp /usr/local/lib/wand/iolib/neopixelLib/neopixelService.service /lib/systemd/system/neopixelService.service
systemctl enable neopixelService.service

# install python requirements
pip install -r /usr/local/lib/wand/iolib/requirements.txt


