#!/bin/bash

set -e

# Eeprom
dtc -@ -I dts -O dtb -o /usr/local/lib/wand/iolib/eepromLib/at24c512.dtbo /usr/local/lib/wand/iolib/eepromLib/at24c512.dts
cp /usr/local/lib/wand/iolib/eepromLib/at24c512.dtbo /boot/overlays/at24c512.dtbo

echo "installing cap1293 drivers"
bash /usr/local/lib/wand/iolib/buttonLib/cap1293/cap12xx_v2/kernel_drivers/install_kernel_module.sh 

echo "installing lp5562 drivers"
bash /usr/local/lib/wand/iolib/indicatorLedLib/kernel_drivers/install_kernel_module.sh

echo "running depmod"
sudo depmod


# install python requirements
pip install -r /usr/local/lib/wand/iolib/requirements.txt


