#!/bin/bash

set -e

# enable i2c

sed /boot/config.txt -i -e "s/^#dtparam=i2c_arm*/dtparam=i2c_arm=on/"
# sed /etc/modules -i -e "s/^#[[:space:]]*\(i2c[-_]dev\)/\1/"
# if ! grep -q "^i2c[-_]dev" /etc/modules; then 
#     printf "i2c-dev\n" >> /etc/modules
# fi

dtparam i2c_arm=on

sed /boot/config.txt -i -e "s/^#dtparam=spi=on/dtparam=spi=on/"
if ! grep -q "^dtparam=spi=on" /boot/config.txt ; then 
    printf "dtparam=spi=on\n" >> /boot/config.txt 
fi

sed /boot/config.txt -i -e "s/^#enable_uart=1/enable_uart=1/"
if ! grep -q "^enable_uart=1" /boot/config.txt ; then 
    printf "enable_uart=1\n" >> /boot/config.txt 
fi


# enablei2c-sensor and max17040

# battery fuel gauge
sed /boot/config.txt -i -e "s/^#dtoverlay=i2c-sensor,max17040/dtoverlay=i2c-sensor,max17040/"
if ! grep -q "^dtoverlay=i2c-sensor,max17040" /boot/config.txt ; then 
    printf "dtoverlay=i2c-sensor,max17040\n" >> /boot/config.txt 
fi

# IO expander
sed /boot/config.txt -i -e "s/^#dtoverlay=mcp23017,i2c_bus=1,i2c_address=0x20,mcp23008,gpiopin=19/dtoverlay=mcp23017,i2c_bus=1,i2c_address=0x20,mcp23008,gpiopin=19/"
if ! grep -q "^dtoverlay=mcp23017,i2c_bus=1,i2c_address=0x20,mcp23008,gpiopin=19" /boot/config.txt ; then 
    printf "dtoverlay=mcp23017,i2c_bus=1,i2c_address=0x20,mcp23008,gpiopin=19\n" >> /boot/config.txt 
fi

# cm4 carrier temp
sed /boot/config.txt -i -e "s/^#dtoverlay=i2c-sensor,lm75,addr=0x48/dtoverlay=i2c-sensor,lm75,addr=0x48/"
if ! grep -q "^dtoverlay=i2c-sensor,lm75,addr=0x48" /boot/config.txt ; then 
    printf "dtoverlay=i2c-sensor,lm75,addr=0x48\n" >> /boot/config.txt 
fi

# kill power on shutdown
sed /boot/config.txt -i -e "s/^#dtoverlay=gpio-poweroff,gpiopin=22,active_low=1/dtoverlay=gpio-poweroff,gpiopin=22,active_low=1/"
if ! grep -q "^dtoverlay=gpio-poweroff,gpiopin=22,active_low=1" /boot/config.txt ; then 
    printf "dtoverlay=gpio-poweroff,gpiopin=22,active_low=1\n" >> /boot/config.txt 
fi

# Eeprom
sed /boot/config.txt -i -e "s/^#dtoverlay=at24c512/dtoverlay=at24c512/"
if ! grep -q "^dtoverlay=at24c512" /boot/config.txt ; then 
    printf "dtoverlay=at24c512\n" >> /boot/config.txt 
fi

# Define bootloader pin state
sed /boot/config.txt -i -e "s/^#gpio=4=dl,op/gpio=4=dl,op/"
if ! grep -q "^gpio=4=dl,op" /boot/config.txt ; then 
    printf "gpio=4=dl,op\n" >> /boot/config.txt 
fi
